spring.application.name=demo

spring.datasource.url=jdbc:postgresql://ep-dark-surf-axu0gf57-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_RjMvkWJlQ9o4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.docker.compose.enabled=false

server.port=8080

jwt.secret=MinhaChaveSuperSecretaQueTemMaisDe32Caracteres123456
jwt.expiration=86400000

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.tool.schema=DEBUG